# Generated by Django 3.1.3 on 2021-01-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_o_number', models.TextField(blank=True, db_column='W/O NUMBER', null=True)),
                ('date', models.TextField(blank=True, db_column='DATE', null=True)),
                ('builder_name', models.TextField(blank=True, db_column='BUILDER NAME', null=True)),
                ('start_time', models.TextField(blank=True, db_column='START TIME', null=True)),
                ('part', models.TextField(blank=True, db_column='PART', null=True)),
                ('customer_field', models.TextField(blank=True, db_column='CUSTOMER:', null=True)),
                ('finish_time_field', models.TextField(blank=True, db_column='FINISH TIME:', null=True)),
                ('tire_size_field', models.TextField(blank=True, db_column='TIRE SIZE:', null=True)),
                ('builder_field', models.TextField(blank=True, db_column='BUILDER #:', null=True)),
                ('machine_field', models.TextField(blank=True, db_column='MACHINE:', null=True)),
                ('treatment_mil_field', models.TextField(blank=True, db_column='TREATMENT MIL:', null=True)),
                ('serial_number_field', models.TextField(blank=True, db_column='SERIAL NUMBER:', null=True)),
                ('rim_diameter_field', models.TextField(blank=True, db_column='RIM DIAMETER:', null=True)),
                ('inches_rubber_field', models.TextField(blank=True, db_column='INCHES RUBBER:', null=True)),
                ('tread_design_field', models.TextField(blank=True, db_column='TREAD DESIGN:', null=True)),
                ('rim_weight_field', models.TextField(blank=True, db_column='RIM WEIGHT:', null=True)),
                ('rim_w_center_field', models.TextField(blank=True, db_column='RIM W/CENTER:', null=True)),
                ('r850_fiber_rubber_weight_field', models.TextField(blank=True, db_column='R850 FIBER:(RUBBER WEIGHT)', null=True)),
                ('r850_fiber_actual_field', models.TextField(blank=True, db_column='R850 FIBER:(ACTUAL)', null=True)),
                ('r803_fiber_rubber_weight_field', models.TextField(blank=True, db_column='R803 FIBER:(RUBBER WEIGHT)', null=True)),
                ('r803_fiber_actual_field', models.TextField(blank=True, db_column='R803 FIBER:(ACTUAL)', null=True)),
                ('number_80_duro_3_rubber_weight_field', models.TextField(blank=True, db_column='80 DURO 3%:(RUBBER WEIGHT)', null=True)),
                ('number_80_duro_3_actual_field', models.TextField(blank=True, db_column='80 DURO 3%:(ACTUAL)', null=True)),
                ('number_80_duro_3_type_rubber_field', models.TextField(blank=True, db_column='80 DURO 3%:(TYPE RUBBER)', null=True)),
                ('number_65_duro_24_rubber_weight_field', models.TextField(blank=True, db_column='65 DURO 24%:(RUBBER WEIGHT)', null=True)),
                ('number_65_duro_24_actual_field', models.TextField(blank=True, db_column='65 DURO 24%:(ACTUAL)', null=True)),
                ('number_65_duro_24_type_rubber_field', models.TextField(blank=True, db_column='65 DURO 24%:(TYPE RUBBER)', null=True)),
                ('setco_45_duro_rubber_weight_field', models.TextField(blank=True, db_column='SETCO 45 DURO:(RUBBER WEIGHT)', null=True)),
                ('setco_45_duro_actual_field', models.TextField(blank=True, db_column='SETCO 45 DURO:(ACTUAL)', null=True)),
                ('setco_45_duro_type_rubber_field', models.TextField(blank=True, db_column='SETCO 45 DURO:(TYPE RUBBER)', null=True)),
                ('number_65_duro_3_rubber_weight_field', models.TextField(blank=True, db_column='65 DURO 3%:(RUBBER WEIGHT)', null=True)),
                ('number_65_duro_3_actual_field', models.TextField(blank=True, db_column='65 DURO 3%:(ACTUAL)', null=True)),
                ('number_65_duro_3_type_rubber_field', models.TextField(blank=True, db_column='65 DURO 3%:(TYPE RUBBER)', null=True)),
                ('build_weight_rubber_weight_field', models.TextField(blank=True, db_column='BUILD WEIGHT:(RUBBER WEIGHT)', null=True)),
                ('build_weight_actual_field', models.TextField(blank=True, db_column='BUILD WEIGHT:(ACTUAL)', null=True)),
                ('flash', models.TextField(blank=True, db_column='FLASH', null=True)),
                ('autoclave', models.TextField(blank=True, db_column='AUTOCLAVE', null=True)),
                ('mold_number', models.TextField(blank=True, db_column='MOLD NUMBER', null=True)),
                ('mold_temp_field', models.TextField(blank=True, db_column='MOLD TEMP:', null=True)),
                ('cure_time', models.TextField(blank=True, db_column='CURE TIME', null=True)),
                ('notes', models.TextField(blank=True, db_column='NOTES', null=True)),
            ],
            options={
                'db_table': 'All records',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_o_number', models.TextField(blank=True, db_column='W/O Number', null=True)),
                ('part_field', models.TextField(blank=True, db_column='PART#', null=True)),
                ('tire_size_field', models.TextField(blank=True, db_column='TIRE SIZE:', null=True)),
                ('inches_rubber_field', models.TextField(blank=True, db_column='INCHES RUBBER:', null=True)),
                ('rim_diameter_field', models.TextField(blank=True, db_column='RIM DIAMETER:', null=True)),
                ('tread_design_field', models.TextField(blank=True, db_column='TREAD DESIGN:', null=True)),
                ('r850_fiber_rubber_weight_field', models.TextField(blank=True, db_column='R850 FIBER:(RUBBER WEIGHT)', null=True)),
                ('r803_fiber_rubber_weight_field', models.TextField(blank=True, db_column='R803 FIBER:(RUBBER WEIGHT)', null=True)),
                ('fiber3', models.TextField(blank=True, db_column='FIBER3', null=True)),
                ('setco_45_duro_rubber_weight_field', models.TextField(blank=True, db_column='SETCO 45 DURO:(RUBBER WEIGHT)', null=True)),
                ('number_65_duro_24_rubber_weight_field', models.TextField(blank=True, db_column='65 DURO 24%:(RUBBER WEIGHT)', null=True)),
                ('number_65_duro_3_rubber_weight_field', models.TextField(blank=True, db_column='65 DURO 3%:(RUBBER WEIGHT)', null=True)),
                ('number_80_duro_3_rubber_weight_field', models.TextField(blank=True, db_column='80 DURO 3%:(RUBBER WEIGHT)', null=True)),
                ('build_weight_rubber_weight_field', models.TextField(blank=True, db_column='BUILD WEIGHT:(RUBBER WEIGHT)', null=True)),
                ('inch2', models.TextField(blank=True, db_column='INCH2', null=True)),
                ('cure_time', models.TextField(blank=True, db_column='CURE TIME', null=True)),
            ],
            options={
                'db_table': 'Item Master',
            },
        ),
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('order_field', models.TextField(blank=True, db_column='Order#', primary_key=True, serialize=False)),
                ('item_number', models.TextField(blank=True, db_column='Item Number', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('number_80', models.IntegerField(blank=True, db_column='80', null=True)),
                ('number_65_24_field', models.TextField(blank=True, db_column='65 24%', null=True)),
                ('number_65_3_field', models.IntegerField(blank=True, db_column='65 3%', null=True)),
                ('number_85', models.IntegerField(blank=True, db_column='85', null=True)),
                ('number_45', models.TextField(blank=True, db_column='45', null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'Production Schedule',
            },
        ),
        migrations.CreateModel(
            name='Wolinktable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_field', models.TextField(blank=True, db_column='WO#', null=True)),
                ('part_field', models.TextField(blank=True, db_column='Part#', null=True)),
                ('customer_field', models.TextField(blank=True, db_column='CUSTOMER:', null=True)),
                ('builders_name', models.TextField(blank=True, db_column='Builders Name', null=True)),
                ('start_time', models.TextField(blank=True, db_column='Start Time', null=True)),
                ('end_time', models.TextField(blank=True, db_column='End Time', null=True)),
                ('builder', models.TextField(blank=True, db_column='Builder', null=True)),
            ],
            options={
                'db_table': 'WOLinkTable',
            },
        ),
    ]
