# Generated by Django 3.1.3 on 2021-01-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allrecords',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='id',
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wolinktable',
            name='id',
        ),
        migrations.AlterField(
            model_name='allrecords',
            name='w_o_number',
            field=models.TextField(blank=True, db_column='W/O NUMBER', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, db_column='Comment', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='w_o_number',
            field=models.TextField(blank=True, db_column='W/O Number', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wolinktable',
            name='wo_field',
            field=models.TextField(blank=True, db_column='WO#', primary_key=True, serialize=False),
        ),
    ]
