# Generated by Django 3.1.3 on 2021-01-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WO', '0003_auto_20210131_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='part_field',
            field=models.TextField(blank=True, db_column='PART#', null=True),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='order_field',
            field=models.TextField(blank=True, db_column='Order#', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wolinktable',
            name='wo_field',
            field=models.TextField(blank=True, db_column='WO#', primary_key=True, serialize=False),
        ),
    ]
